// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteLogin():Promise<Record<string, any>>;

export function GetAnalytics(arg1:number):Promise<Record<string, any>>;

export function GetJobs():Promise<Array<Record<string, any>>>;

export function GetJobsFromCache():Promise<Array<Record<string, any>>>;

export function GetLastSyncTime():Promise<string>;

export function GetUserInfo():Promise<Record<string, any>>;

export function GetWorkspaces():Promise<Array<Record<string, any>>>;

export function GetWorkspacesFromCache():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;
