// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteLogin() {
  return window['go']['main']['App']['CompleteLogin']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetJobsFromCache() {
  return window['go']['main']['App']['GetJobsFromCache']();
}

export function GetLastSyncTime() {
  return window['go']['main']['App']['GetLastSyncTime']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function GetWorkspacesFromCache() {
  return window['go']['main']['App']['GetWorkspacesFromCache']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}
